name: mie429

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - matplotlib
  - notebook
  - cpuonly
  - pytorch
  - torchvision
  - conda-forge::torchdata # pytorch channel uses never version of glibc

  - pip:
    - flake8
    - pydicom
    - opencv-python